### ISSUE TITLE
No Noisemake alerts for BAU users

### ISSUE THREAD

**Issue by AlternateMew** [D1GQ/BetterAmongUs#10]
The role works fine for vanilla users, but BAU users get no noise nor icon.
![image](https://github.com/user-attachments/assets/d83b5769-0fc7-4dec-b297-daa730cba28e)
![image](https://github.com/user-attachments/assets/65981224-a346-4bb7-ba7e-8017e3837b08)

**Comment by D1GQ** [comment]
Fixed
