### ISSUE TITLE
False positive anticheat case

### ISSUE THREAD

**Issue by AlternateMew** [D1GQ/BetterAmongUs#11]
Playing as client, had Anticheat enabled (hoped I could alert the host if BAU spotted a cheat)
Anticheat detected impostor killing and flagged it as cheating.
![image](https://github.com/user-attachments/assets/777c1711-97cf-4338-8483-f83b95a95b69)
![image](https://github.com/user-attachments/assets/5731fff5-fde9-44df-a4bd-6cea76e67c87)

**Comment by D1GQ** [comment]
Need logs

**Comment by AlternateMew** [comment]
Unfortunately logs on this one were overwritten and it's not seeming to trigger in a controlled environment. If a repeat happens I'll make sure to grab logs.

**Comment by D1GQ** [comment]
Probably has something to do with checking the players kill cooldown, I have temporarily commented out and will release a hot fix soon!

**Comment by D1GQ** [comment]
Fixed!

**Comment by AlternateMew** [comment]
Log gotten!

Not sure if present in Hotfix 2, was still on Canary 5 Hotfix 1 and managed to get a log of the false positive. 
Switched to Hotfix 2 right after grabbing the log. 

Extra info: Host was using Sicko to help detect/ban others who join from public with it. The false positive player was not. 
Happens at 23:41

[better-log_FalsePositive.txt](https://github.com/user-attachments/files/16485388/better-log_FalsePositive.txt)
