### ISSUE TITLE
Ghost chat bubbles are not transparent.

### ISSUE THREAD

**Issue by AlternateMew** [D1GQ/BetterAmongUs#6]
It's a bit difficult to tell who's a fellow ghost talking and who's talking alive.

**Comment by D1GQ** [comment]
May I get a screenshot on what you're talking about?

**Comment by AlternateMew** [comment]
Screenshot!
![image](https://github.com/user-attachments/assets/717ed59a-feae-47b8-98ce-cab820c5c5d5)

**Comment by D1GQ** [comment]
Fixed!
